service: service-todo
frameworkVersion: '2 || 3'

custom:
  todoTable: 'todo-${sls:stage}'
  eventLogTable: 'todo-event-log-${sls:stage}'

provider:
  name: aws
  region: 'us-east-1'
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt TodosTable.Arn
            - !GetAtt TodoEventLogTable.Arn
        - Effect: Allow
          Action:
            - sns:*
          Resource:
            - !GetAtt TodosTopic.Arn
  environment:
    TODOS_TABLE: ${self:custom.todoTable}
    TODOS_EVENT_LOG_TABLE: ${self:custom.eventLogTable}

functions:
  addTodo:
    handler: src/addTodo.handler
    events:
      - httpApi:
          method: POST
          path: /todos

  onTodoCreated:
    handler: src/onTodoCreated.handler
    events:
      - sns:
          topic: !GetAtt TodoCreatedEvent.Arn

  getTodos:
    handler: src/getTodos.handler
    events:
      - httpApi:
          method: GET
          path: /todos

  getTodo:
    handler: src/getTodo.handler
    events:
      - httpApi:
          method: GET
          path: /todos/{id}

  updateTodo:
    handler: src/updateTodo.handler
    events:
      - httpApi:
          method: PUT
          path: /todos/{id}
      - httpApi:
          method: POST
          path: /todos/{id}

  deleteTodo:
    handler: src/deleteTodo.handler
    events:
      - httpApi:
          method: DELETE
          path: /todos/{id}

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.todoTable}

    TodoEventLogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: entityId
            AttributeType: S
          - AttributeName: event
            AttributeType: S
          - AttributeName: header # should include timestamp or revision number for ordering
            AttributeType: M
          - AttributeName: payload
            AttributeType: M
        KeySchema:
          - AttributeName: entityId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.eventLogTable}

    CreateTodoEvent:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: create-todo
        DisplayName: Create Todo

    TodoCreatedEvent:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: todo-created
        DisplayName: Todo Created

    MarkTodoCompleteEvent:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: mark-todo-complete
        DisplayName: Create Todo

    TodoCompletedEvent:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: todo-completed
        DisplayName: Create Todo




