service: service-todo
frameworkVersion: '2 || 3'

custom:
  tableName: 'todo-${sls:stage}'

provider:
  name: aws
  region: 'us-east-1'
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt TodosTable.Arn
  environment:
    TABLE_NAME: ${self:custom.tableName}

functions:
  addTodo:
    handler: src/addTodo.handler
    events:
      - httpApi:
          method: POST
          path: /todos

  getTodos:
    handler: src/getTodos.handler
    events:
      - httpApi:
          method: GET
          path: /todos

  getTodo:
    handler: src/getTodo.handler
    events:
      - httpApi:
          method: GET
          path: /todos/{id}

  updateTodo:
    handler: src/updateTodo.handler
    events:
      - httpApi:
          method: PUT
          path: /todos/{id}
      - httpApi:
          method: POST
          path: /todos/{id}

  deleteTodo:
    handler: src/deleteTodo.handler
    events:
      - httpApi:
          method: DELETE
          path: /todos/{id}

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
